base.url=https://demowebshop.tricentis.com
browser=chromium
headless=false
default.timeout=10000
screenshots.dir=build/screenshots
test.user.email=CHANGE_ME_IN_LOCAL_PROPERTIES
test.user.password=CHANGE_ME_IN_LOCAL_PROPERTIES